
Config = {
    DrawDistance = 10.0,
    KeyToOpen = 38,
    OutfitPrice = 750,
    OutfitPurchasePrice = 100,
    
    ComponentPrices = {
        torso_1 = 100,
        tshirt_1 = 50,
        arms = 50,
        pants_1 = 75,
        shoes_1 = 50,
        accessories = 25
    },
    
    AccessoryPrices = {
        masque = 50,
        chapeau = 30,
        lunettes = 25,
        montres = 75,
        oreilles = 20,
        bracelet = 30,
        sac = 60,
        gilet = 100
    },
    
    ItemDefinitions = {
        cloth = 'cloth',               
        cloth_torso = 'cloth_torso',   
        cloth_tshirt = 'cloth_tshirt', 
        cloth_arms = 'cloth_arms',     
        cloth_pants = 'cloth_pants',   
        cloth_shoes = 'cloth_shoes',   
        
        cloth_mask = 'cloth_mask',      
        cloth_hat = 'cloth_helmet',      
        cloth_glasses = 'cloth_glasses', 
        cloth_watch = 'cloth_watches',   
        cloth_ears = 'cloth_ears',       
        cloth_bracelet = 'cloth_bracelets', 
        cloth_bag = 'cloth_bags',        
        cloth_vest = 'cloth_bproof',     
        cloth_chain = 'cloth_chain'      
    },
    
    Shops = {
        {
            name = "Magasin de vêtements",
            position = vector3(72.3, -1399.1, 28.4),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Magasin de vêtements",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        },
        {
            name = "Binco",
            position = vector3(425.1, -806.2, 28.5),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Binco",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        },
        {
            name = "Suburban",
            position = vector3(127.0, -223.8, 53.6),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Suburban",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        },
        {
            name = "Ponsonbys",
            position = vector3(-163.7, -302.6, 38.7),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Ponsonbys",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        },
        {
            name = "Discount Store",
            position = vector3(1693.3, 4822.7, 41.1),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Discount Store",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        },
        {
            name = "Grapeseed",
            position = vector3(1196.6, 2710.2, 37.2),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Magasin de vêtements",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        },
        {
            name = "Paleto Bay",
            position = vector3(-1100.5, 2710.6, 18.1),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Magasin de vêtements",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        },
        {
            name = "Chumash",
            position = vector3(-3170.5, 1044.6, 19.9),
            blipEnabled = true,
            blipSprite = 73,
            blipColor = 47,
            blipScale = 0.7,
            blipLabel = "Magasin de vêtements",
            markerEnabled = true,
            markerType = 1,
            markerSizeX = 1.5,
            markerSizeY = 1.5,
            markerSizeZ = 0.5,
            markerColorR = 50,
            markerColorG = 200,
            markerColorB = 50,
            markerColorA = 100,
            markerBobUpAndDown = false,
            markerFaceCamera = false,
            markerRotate = false
        }
    },

    AccessorySubcategories = {
        masque = { component = 1, props = false, label = "Masque" },
        chapeau = { component = 0, props = true, label = "Chapeau" },
        lunettes = { component = 1, props = true, label = "Lunettes" },
        montres = { component = 6, props = true, label = "Montres" },
        oreilles = { component = 2, props = true, label = "Oreilles" },
        bracelet = { component = 7, props = true, label = "Bracelet" },
        sac = { component = 5, props = false, label = "Sac" },
        gilet = { component = 9, props = false, label = "Gilet" }
    }
} 